function r = test_allocation_optimality()
%TEST_ALLOCATION_OPTIMALITY  The greedy's optimality claims, measured not remembered.
%
%   Two claims in marginal_spares_allocation.m used to lean on "an exact
%   dynamic program" that existed nowhere in the repository -- the numbers
%   it supposedly produced could not be regenerated by anyone, including
%   us. This test IS that program. On a fixed demo-scale configuration it
%   (1) checks the affordability-masked greedy against an exact
%   budget-indexed DP for the EXPECTED-BACKORDER objective at every point
%   of the greedy's own trace, and (2) re-measures the cost of the old
%   stop-at-first-unaffordable rule. The docstrings now quote THIS test's
%   output and nothing else.
%
%   Scope, stated exactly: the DP minimises total expected backorders,
%   which is the greedy's own objective. Availability weights each part's
%   backorders differently, so the availability-optimal allocation is a
%   different (and combinatorial) problem that neither the greedy nor this
%   DP solves; availabilities are printed for scale, not claimed optimal.

    r = struct('name', 'allocation: greedy vs exact DP (EBO objective)', ...
               'pass', true, 'lines', {{}});

    cost = [1200 3400 890 15000 2100 640 320 8800 4500 1750 990 26000]';
    qty  = [2 1 1 2 1 1 4 1 1 2 1 1]';
    Z    = 24; budget = 40000; s_max = 30;
    base = [2.9 3.2 2.9 2.9 3.3 2.9 8.3 1.3 9.9 2.6 1.9 1.2];
    dem  = struct('Lambda', [base; 1.15 * base]);

    ebo_tab = expected_backorders(dem.Lambda, s_max);
    ebo0    = sum(ebo_tab(1, :));

    alloc = marginal_spares_allocation(dem, cost, Z, qty, budget, s_max);

    gran = cost(1);
    for i = 2:numel(cost), gran = gcd(gran, cost(i)); end
    [f, dp_alloc] = ebo_dp(ebo_tab, cost, budget, gran);

    % (1) prefix optimality at every greedy spend point
    worst = 0; ebo_run = ebo0;
    for s = 1:numel(alloc.trace)
        tr = alloc.trace(s);
        ebo_run = ebo_run - tr.dEBO;
        b = round(tr.cum_cost / gran);
        worst = max(worst, ebo_run - f(b + 1));
    end
    % Exact equality is NOT attainable in general: with unequal integer
    % costs the per-dollar greedy can sit a hair above the DP at some
    % spends (measured here: ~2e-3 backorders on totals of ~20). The old
    % docstring said "holds exactly"; this test is what replaced that
    % claim with a measured bound.
    ok = worst <= 0.01;
    r = add(r, ok, sprintf(['  every greedy prefix is within %.1e backorders of the exact DP ' ...
                            'at its own spend (%d steps; exact equality is not guaranteed ' ...
                            'for unequal integer costs)'], worst, numel(alloc.trace)));

    % (2) the old stop rule, re-measured on this configuration
    [s_old, spent_old] = stop_rule(ebo_tab, cost, budget, s_max);
    ebo_old  = per_part(ebo_tab, s_old);
    ebo_grd  = per_part(ebo_tab, alloc.stock);
    ebo_dpa  = per_part(ebo_tab, dp_alloc);
    A_old = fleet_availability(ebo_old, Z, qty);
    A_grd = fleet_availability(ebo_grd, Z, qty);
    A_dp  = fleet_availability(ebo_dpa, Z, qty);
    ok = sum(ebo_dpa) <= sum(ebo_grd) + 1e-9 && sum(ebo_grd) <= sum(ebo_old) + 1e-9;
    r = add(r, ok, sprintf(['  EBO at $%d: exact DP %.3f <= masked greedy %.3f <= old stop-rule %.3f ' ...
                            '(stop-rule left $%d unspent)'], ...
                           budget, sum(ebo_dpa), sum(ebo_grd), sum(ebo_old), round(budget - spent_old)));
    % informational line, deliberately without a PASS tag: an assertion
    % that cannot fail would only inflate the pass count
    r.lines{end+1} = sprintf(['  availability: old stop-rule %.3f | masked greedy %.3f | EBO-DP ' ...
                              'allocation %.3f (printed for scale; availability-optimal not computed)'], ...
                             A_old, A_grd, A_dp);
end

% ---------------------------------------------------------------------

function e = per_part(tab, s)
    N = numel(s); e = zeros(N, 1);
    for i = 1:N, e(i) = tab(s(i) + 1, i); end
end

function [s, spent] = stop_rule(tab, cost, budget, s_max)
%  The documented defect, reproduced: rank ALL candidates by marginal
%  return per dollar and STOP the first time the best one is unaffordable.
    N = numel(cost); s = zeros(N, 1); spent = 0;
    while true
        gain = -inf(N, 1);
        for i = 1:N
            if s(i) < s_max
                gain(i) = (tab(s(i) + 1, i) - tab(s(i) + 2, i)) / cost(i);
            end
        end
        [g, i] = max(gain);
        if ~isfinite(g) || g <= 0, break; end
        if spent + cost(i) > budget, break; end   % the bug: a stop, not a mask
        s(i) = s(i) + 1; spent = spent + cost(i);
    end
end

function [f, alloc] = ebo_dp(tab, cost, budget, gran)
%  Exact minimum total EBO at every budget multiple of gran, by a
%  multiple-choice DP over parts; alloc is one optimal allocation at the
%  full budget, recovered by backtracking.
    [S1, N] = size(tab); s_max = S1 - 1;
    B = floor(budget / gran);
    f = zeros(1, B + 1);
    choice = zeros(N, B + 1);
    for i = 1:N
        ci = round(cost(i) / gran);
        g = inf(1, B + 1); ch = zeros(1, B + 1);
        for s = 0:s_max
            cs = s * ci;
            if cs > B, break; end
            cand = [inf(1, cs), f(1:B + 1 - cs)] + tab(s + 1, i);
            upd = cand < g;
            g(upd) = cand(upd); ch(upd) = s;
        end
        f = g; choice(i, :) = ch;
    end
    alloc = zeros(N, 1); b = B;
    for i = N:-1:1
        alloc(i) = choice(i, b + 1);
        b = b - alloc(i) * round(cost(i) / gran);
    end
end

function r = add(r, ok, line)
    r.pass = r.pass && ok;
    if ok, tag = 'PASS'; else, tag = 'FAIL'; end
    r.lines{end+1} = sprintf('%s  %s', line, tag);
end
